services:
  app:
    build: .
    container_name: stageconnect_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: StageConnect
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://127.0.0.1:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: stageconnect
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database
      MAIL_MAILER: log
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: stageconnect_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stageconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
